import { type NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import math from 'mathjs'
import { readlink } from 'fs'

const randInt = (min: number, max: number) => {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

const Home: NextPage = () => {
  const [target, setTarget] = useState<number>(0)
  const [numbers, setNumbers] = useState<number[]>([])

  useEffect(() => {
    const nums = []
    for (let i = 0; i < 6; i++) {
      nums.push(randInt(1, 25))
    }

    const t = randInt(100, 500)
    setNumbers(nums)
    setTarget(t)
  }, [])
  return (
    <>
      <Head>
        <title>Digits</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-950">
        <h1>{target}</h1>
      </main>
    </>
  )
}

export default Home
